### ISSUE TITLE
Incorrect information as of 9/8/2021

### ISSUE THREAD

**Issue by DylanPerkins** [tournament-kings/wiki#1]
The Support Bot category says the bot is available as a premium-only option, although it is actually open to every as an early access bot. This may draw confusion and miss interpretation for users that are not in the Tournament King's support hub Discord.

![Support bot (issue)](https://user-images.githubusercontent.com/88121080/128760168-23128100-83f1-4dcc-ad56-240993f356cb.png)

**Comment by EckyYakov** [comment]
Updated to say 'Early Access'. Thank you!
